### ISSUE TITLE
Do the CSV ingestion methods check/enforce expected column headers? 

### ISSUE THREAD

**Issue by walker-philips** [SaguaroCapital/SaguaroTrader.jl#4]
Curious how the program handles expected vs required vs unexpected column headers

**Comment by tylerjthomas9** [comment]
I just added a commit to expose the functionality to rename market data columns. By default, it assumes that the market data has the same naming as `MarketData.jl`. 

PR: https://github.com/SaguaroCapital/SaguaroTrader.jl/pull/5

Now, you can specify `time_col`, `open_col` and `close_col` when creating the `CSVDailyBarSource`
